# Generated by Django 5.2.9 on 2025-12-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
