# Generated by Django 5.2.9 on 2025-12-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_useraccount_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
